"""empty message

Revision ID: 0c6965c85c0f
Revises: 4ba144c76f4d
Create Date: 2023-12-25 23:32:08.202866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c6965c85c0f'
down_revision: Union[str, None] = '4ba144c76f4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('tag1', sa.String(), nullable=False))
    op.add_column('questions', sa.Column('tag2', sa.String(), nullable=False))
    op.add_column('questions', sa.Column('tag3', sa.String(), nullable=False))
    op.add_column('questions', sa.Column('img', sa.Text(), nullable=True))
    op.drop_column('questions', 'topic')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('topic', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('questions', 'img')
    op.drop_column('questions', 'tag3')
    op.drop_column('questions', 'tag2')
    op.drop_column('questions', 'tag1')
    # ### end Alembic commands ###
