"""empty message

Revision ID: 0fd13895bad8
Revises: 0c6965c85c0f
Create Date: 2023-12-25 23:41:26.666713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fd13895bad8'
down_revision: Union[str, None] = '0c6965c85c0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'tag2',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('questions', 'tag3',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'tag3',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('questions', 'tag2',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
