"""empty message

Revision ID: 6176e9b8b8ab
Revises: a7a6e2ddb08f
Create Date: 2023-12-27 18:09:41.607298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6176e9b8b8ab'
down_revision: Union[str, None] = 'a7a6e2ddb08f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_question_user_uc', 'practices', ['question_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_question_user_uc', 'practices', type_='unique')
    # ### end Alembic commands ###
