"""empty message

Revision ID: c18b02e2a6b3
Revises: 217b19afff73
Create Date: 2023-12-27 15:12:50.606838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c18b02e2a6b3'
down_revision: Union[str, None] = '217b19afff73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practices', sa.Column('practice_date', sa.Date(), nullable=True))
    op.add_column('practices', sa.Column('repeat_date', sa.Date(), nullable=True))
    op.add_column('questions', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'user_id')
    op.drop_column('practices', 'repeat_date')
    op.drop_column('practices', 'practice_date')
    # ### end Alembic commands ###
