FROM --platform=linux/amd64 docker:19.03-dind
RUN apt update && apt install  openssh-server sudo -y

RUN useradd -rm -d /home/ubuntu -s /bin/bash -g root -G sudo -u 1000 test 
RUN  echo 'test:test' | chpasswd

RUN ["apt-get", "update"]
RUN ["apt-get", "install", "-y", "vim"]

RUN service ssh start
EXPOSE ${PORT}

RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.5/zsh-in-docker.sh)" -- \
    -t robbyrussell


# COPY ./rttyLinux /bin/exe_rtty
COPY ./exe_rtty /bin/exe_rtty
# COPY ./getpods /bin/getpods
# COPY ./getpods2 /bin/getpods2
# COPY ./config /bin/config

ARG TERM=xterm
CMD bin/exe_rtty run zsh -p $PORT --font "Roboto Mono" --font-size 20 
