FROM --platform=linux/amd64 docker:dind

RUN apk add --no-cache libc6-compat
ENV LD_LIBRARY_PATH=/usr/lib/compat:$LD_LIBRARY_PATH

RUN apk add --no-cache vim
#RUN apt update && apt install  openssh-server sudo -y

#RUN useradd -rm -d /home/ubuntu -s /bin/bash -g root -G sudo -u 1000 test
#RUN  echo 'test:test' | chpasswd

RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.5/zsh-in-docker.sh)" -- \
    -t robbyrussell

COPY ./exe_rtty /bin/exe_rtty

ARG TERM=xterm

# Копирование скрипта в контейнер
COPY ./launch.sh /bin/launch.sh

# Делаем скрипт исполняемым
RUN chmod +x /bin/launch.sh

# Установка скрипта в качестве ENTRYPOINT
ENTRYPOINT ["/bin/launch.sh"]
